### PR TITLE
React for a react community 

### PR DESCRIPTION
**Pull request by staticfrost**
I've ported the site across to a create-react-app.

A react community website should always have react on it.

### CODE REVIEW

**Comment by loklaan** [comment]
Haha thanks - I initially went to use CRA but I didn't want to skimp on load perf, so I went plain ol' html/css. This was built & deployed in under 30mins.

I'd love for this to be built in React, so if you're up for the challenge, could you extend this PR to prerender the app into plain html / css?

**Comment by staticfrost** [comment]
I'm a noob when it comes to react, but I like to take on projects so I think I'd like to give it ago. 

Cheers.

**Comment by loklaan** [comment]
Oh cool, that's great to hear! I'd love the help.

Places to start looking, for prerendering a react site, is just to google those terms 😂. Also, key tech to find are webpack plugins or react frameworks, like the [prerender-loader](https://github.com/GoogleChromeLabs/prerender-loader) and [Gatsby](https://www.gatsbyjs.org/).

But please keep in mind that this is the first version of the site, and it'll be torn down at some point within the next few months!

**Comment by loklaan** [comment]
I ended up porting it to next.js in anticipation for a couple server-side features.

**Pull request closed without merging**
